<!DOCTYPE HTML>
<html lang="en">


<head>
<?php include 'head'; ?>
<title>Securing your wallet - Umkoin</title>
</head>


<body>


<?php
include 'page_head.php';
?>


<div class="body">

  <div class="breadcrumbs"></div>

  <div id="content" class="content">

    <h1>Securing your wallet</h1>
    <p class="summarytxt">Like in real life, your wallet must be secured. Umkoin makes it possible to transfer value anywhere in a very easy way and it allows you to be in control of your money. Such great features also come with great security concerns. At the same time, Umkoin can provide very high levels of security if used correctly. <b>Always remember that it is your responsibility to adopt good practices in order to protect your money</b>.</p>

    <h2 id="online"><img src="/img/icons/ico_warning.svg" class="titleicon" alt="warning">Be careful with online services</h2>
    <p>You should be wary of any service designed to store your money online. Many exchanges and online wallets suffered from security breaches in the past and such services generally still do not provide enough insurance and security to be used to store money like a bank. Accordingly, you might want to use other types of <a href="/en/choose-your-wallet.php">Umkoin wallets</a>. Otherwise, you should choose such services very carefully. Additionally, using two-factor authentication is recommended.</p>

    <h2 id="everyday">Small amounts for everyday uses</h2>
    <p>A Umkoin wallet is like a wallet with cash. If you wouldn't keep a thousand dollars in your pocket, you might want to have the same consideration for your Umkoin wallet. In general, it is a good practice to keep only small amounts of umkoins on your computer, mobile, or server for everyday uses and to keep the remaining part of your funds in a safer environment.</p>

    <h2 id="backup">Backup your wallet</h2>
    <p>Stored in a safe place, a backup of your wallet can protect you against computer failures and many human mistakes.  It can also allow you to recover your wallet after your mobile or computer was stolen if you keep your wallet encrypted.</p>

    <div class="box">

      <h3 id="backupwhole">Backup your entire wallet</h3>
      <p>Some wallets use many hidden private keys internally. If you only have a backup of the private keys for your visible Umkoin addresses, you might not be able to recover a great part of your funds with your backup.</p>

      <h3 id="backuponline">Encrypt online backups</h3>
      <p>Any backup that is stored online is highly vulnerable to theft. Even a computer that is connected to the Internet is vulnerable to malicious software. As such, encrypting any backup that is exposed to the network is a good security practice.</p>

      <h3 id="backupmany">Use many secure locations</h3>
      <p>Single points of failure are bad for security. If your backup is not dependent of a single location, it is less likely that any bad event will prevent you to recover your wallet. You might also want to consider using different medias like USB keys, papers and CDs.</p>

      <h3 id="backupregular">Make regular backups</h3>
      <p>You need to backup your wallet on a regular basis to make sure that all recent Umkoin change addresses and all new Umkoin addresses you created are included in your backup. However, all applications will be soon using wallets that only need to be backed up once.</p>

    </div>

    <h2 id="encrypt">Encrypt your wallet</h2>
    <p>Encrypting your wallet or your smartphone allows you to set a password for anyone trying to withdraw any funds. This helps protect against thieves, though it cannot protect against keylogging hardware or software.</p>

    <div class="box">

      <h3 id="encryptforget">Never forget your password</h3>
      <p>You should make sure you never forget the password or your funds will be permanently lost. Unlike your bank, there are very limited password recovery options with Umkoin. In fact, you should be able to remember your password even after many years without using it. In doubt, you might want to keep a paper copy of your password in a safe place like a vault.</p>

      <h3 id="encryptstrong">Use a strong password</h3>
      <p>Any password that contains only letters or recognizable words can be considered very weak and easy to break. A strong password must contain letters, numbers, punctuation marks and must be at least 16 characters long. The most secure passwords are those generated by programs designed specifically for that purpose. Strong passwords are usually harder to remember, so you should take care in memorizing it.</p>

    </div>

    <h2 id="offline">Offline wallet for savings</h2>
    <p>An offline wallet, also known as cold storage, provides the highest level of security for savings. It involves storing a wallet in a secured place that is not connected to the network. When done properly, it can offer a very good protection against computer vulnerabilities. Using an offline wallet in conjunction with backups and encryption is also a good practice. Here is an overview of some approaches.</p>

    <div class="box boxexpand">

      <h3 id="offlinetx"><a onclick="boxShow(event);" ontouchstart="boxShow(event);" class="link-js">Offline transaction signing</a></h3>
      <p>This approach involves having two computers sharing some parts of the same wallet. The first one must be disconnected from any network. It is the only one that holds the entire wallet and is able to sign transactions. The second computer is connected to the network and only has a watching wallet that can only create unsigned transactions. This way, you can securely issue new transactions with the following steps.</p>
      <ol>
        <li>Create a new transaction on the online computer and save it on an USB key.</li>
        <li>Sign the transaction with the offline computer.</li>
        <li>Send the signed transaction with the online computer.</li>
      </ol>
      <p>Because the computer that is connected to the network cannot sign transactions, it cannot be used to withdraw any funds if it is compromised.</p>

    </div>

    <br>

    <div class="box boxexpand">

      <h3 id="hardwarewallet"><a onclick="boxShow(event);" ontouchstart="boxShow(event);" class="link-js">Hardware wallets</a></h3>
      <p>Hardware wallets are the best balance between very high security and ease of use. These are little devices that are designed from the root to be a wallet and nothing else. No software can be installed on them, making them very secure against computer vulnerabilities and online thieves. Because they can allow backup, you can recover your funds if you lose the device.</p>

    </div>

    <h2 id="update">Keep your software up to date</h2>
    <p>Using the latest version of your Umkoin software allows you to receive important stability and security fixes. Updates can prevent problems of various severity, include new useful features and help keep your wallet safe. Installing updates for all other software on your computer or mobile is also important to keep your wallet environment safer.</p>

    <h2 id="offlinemulti">Multi-signature to protect against theft</h2>
    <p>Umkoin includes a multi-signature feature that allows a transaction to require multiple independent approvals to be spent. This can be used by an organization to give its members access to its treasury while only allowing a withdrawal if 3 of 5 members sign the transaction. Some web wallets also provide multi-signature wallets, allowing the user to keep control over their money while preventing a thief from stealing funds by compromising a single device or server.</p>

    <h2 id="offlinetestament">Think about your testament</h2>
    <p>Your umkoins can be lost forever if you don't have a backup plan for your peers and family. If the location of your wallets or your passwords are not known by anyone when you are gone, there is no hope that your funds will ever be recovered. Taking a bit of time on these matters can make a huge difference.</p>

  </div>

</div>


<?php
include 'page_footer.php';
?>


</body>
</html>
